# Generated by Django 3.2.9 on 2023-10-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedtext',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
